project:
  type: website

website:
  title: "Coding Café"
  navbar:
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

