project:
  type: website

website:
  title: "R coding café at Steno Diabetes Center Aarhus and the Department of Publi Health, Aarhus University"
  navbar:
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

