project:
  type: sdca-theme
  render: 
    - "*.qmd"
    - "*.md"
    - "*.Rmd"
    - "!advertisement/"

website:
  title: "Coding Café"
  site-url: "https://coding-cafe-sdca-au.netlify.com"
  repo-url: "https://github.com/steno-aarhus/coding-cafe"
  navbar:
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
      - icon: globe
        href: directory.qmd

format: sdca-theme-html

editor: 
  markdown:
    wrap: 72
    canonical: true
