---
title: "Coding Café"
subtitle: "Steno Diabetes Center Aarhus and Aarhus University"
page-layout: full
execute: 
  message: false
  warning: false
  echo: false
---

Welcome to the Coding Café at the [Steno Diabetes Center
Aarhus](https://www.stenoaarhus.dk/forskning/) (SDCA) and the
[Department of Public Health at Aarhus University](https://ph.au.dk/)
(AU-PH).

The Coding Café is a bi-weekly open "café" for anyone working at SDCA,
Aarhus University Hospital, Department of Public Health, Department of
Clinical Medicine and Department of Biomedicine, Aarhus University to go
and get assistance with **coding** in R. The only prerequisite so far is
that you have had some type of introduction to R, preferably through a
course such as [this](https://r-cubed-intro.rostools.org/) offered by
the Danish Diabetes and Endocrinology Academy or similar introductory
courses.

The sessions are open and anyone can join in and out at anytime during
the allotted time. There will be two instructors with experience working
in R. We also highly encourage the participants to interact with each
other - maybe there is someone in the group that has the solution to
your problem.

During the sessions there will be coffee and tea - or whatever. If you
want to get a calendar invitation to also receive updates if rooms or
times are changed, please send an email to Daniel Ibsen,
[dbi\@ph.au.dk](mailto:dbi@ph.au.dk). Otherwise, the latest schedule
will always be on this website.

## Upcoming schedule - Schedule for 2024 semester coming soon!

```{r tbl-schedule}
#| tbl-cap: "Upcoming dates, times, and locations for the Café sessions."
schedule <- read.csv(here::here("data", "schedule.csv"))
knitr::kable(schedule)
```

## Practical information

### Things to do before asking for help

Being a good coder in R does not necessarily mean that one just sits
down and writes a lot of code like writing a piece of text. Even
experienced R users search online for code. The great thing about R is
that there is often multiple solutions to a coding problem. What often
separates an experienced user from a new user is that the experienced
user know what to search for, where to search and understand the
replies.

We suggest that you try to search on either Google or directly in
[Stackoverflow](https://stackoverflow.com/). As a next step, it can be
useful to use AI-tools like ChatGPT-3 but beware that it can make up
functions and that it does not always work.

These are suggestions to try before asking a question.

### Asking a clear coding question

Some issues are simple such as I cannot download this package. Other
times what you want to do is more complex and needs a bit of background
for a person outside your project to understand what you want to do.
Therefore, you need to prepare and provide the context to the person you
are asking for help. This could be in the form of showing the structure
of your dataset, which functions you used, and what you have tried so
far.

### Note about sensitive data

Many of us work with very sensitive data - especially those working in
Denmark's Statistics (DST). If you are working on DST, or something
similar where you are not allowed to show the data to anyone else, you
need to prepare your question a bit more. We recommend that you find an
example dataset that looks similar to the dataset you work with and make
a coding example.

<!-- ## Blogs -->
